### ISSUE TITLE
using the code from proxy server

### ISSUE THREAD

**Issue by dahuoji** [kevinspencer/WWW-LongURL#1]
Dear Kevin,
Could you please let me know that if it's possible to use your script on computing nodes which can only connect to Internet via a proxy server? If yes, then how to set? Since I have large data set to run, I was trying to use some cluster, and I got stuck in this problem. I would appreciate if you could help me out. Thank you in advance.

Bests,
Huijing

**Comment by kevinspencer** [comment]
Hi, if you have a specific issue with the code then I'd be more than happy to assist.  Just let me know.
